spring:
  datasource:
    url: jdbc:tc:postgresql:15-alpine:///app_database_test
    username: test
    password: test
    driver-class-name: org.testconteiners.jdbc.ContainerDatabaseDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

